# Generated by Django 5.2 on 2025-05-10 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='technical_condition',
            field=models.CharField(choices=[('Исправно', 'Исправно'), ('Неисправно', 'Неисправно')], default='Исправно', max_length=20, verbose_name='Техническое состояние'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_number',
            field=models.CharField(default='Н/Д', max_length=50, verbose_name='Номер транспорта'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='deliveries/', verbose_name='Медиафайл'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateTimeField(verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Дистанция (км)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.packagingtype', verbose_name='Упаковка'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='service',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.deliverystatus', verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.transporttype', verbose_name='Модель транспорта'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service',
            field=models.ManyToManyField(related_name='deliveries', to='deliveries.servicetype', verbose_name='Услуги'),
        ),
    ]
